#
services:

  frontend-prod:
    container_name: frontend-prod
    build:
      context: ./frontend
      target: nginx-prod
    environment:
      NODE_ENV: production
    depends_on:
      backend-prod:
        condition: service_healthy
    ports:
      - 81:80
    expose:
      - 81
    volumes:
      - /opt/point-cache/cache:/opt/cache:rw

  backend-prod:
    container_name: backend-prod
    build:
      context: ./backend
      target: production
    environment:
      NODE_ENV: production
    ports:
      - 8880:8880
    expose:
      - 8880
    depends_on:
      postgres-prod:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend-prod:8880/api/healthcheck" ]
      interval: 60s
      timeout: 5s
      retries: 2

  postgres-prod:
    container_name: dbpv-container-prod
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbpv
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5435:5432
    expose:
      - 5435
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/prod/postgres/pgdata:/var/lib/postgresql/data/pgdata
